## The Sequential model

Setup

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

Define Sequential model

In [3]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)

In [4]:
x = tf.ones((3, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [6]:
y = model(x)
print(y)

tf.Tensor(
[[-0.00204086  1.7289034   0.5635878  -0.9435637 ]
 [-0.00204086  1.7289034   0.5635878  -0.9435637 ]
 [-0.00204086  1.7289034   0.5635878  -0.9435637 ]], shape=(3, 4), dtype=float32)


In [8]:
model.layers

another method to add layer

In [9]:
model = keras.Sequential()
model.add(layers.Dense(2, activation="relu"))
model.add(layers.Dense(3, activation="relu"))
model.add(layers.Dense(4))

In [10]:
print(len(model.layers))

3


In [11]:
model.pop()
print(len(model.layers))

2


In [12]:
model.layers

Specifying the input shape in advance

In [13]:
layer = layers.Dense(3)
layer.weights

[]

In [16]:
x = tf.ones((3, 3))
y = layer(x)
print(layer.weights)

[<tf.Variable 'dense_5/kernel:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.22079706, -0.57878137, -0.1959784 ],
       [-0.30124426,  0.9408088 , -0.3164854 ],
       [-0.19284964,  0.08592725,  0.4561491 ]], dtype=float32)>, <tf.Variable 'dense_5/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]


In [18]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
) 

x = tf.ones((1, 4))
y = model(x)
print("Number of weights after calling the model:", len(model.weights))  

Number of weights after calling the model: 6


In [19]:
model.weights

[<tf.Variable 'sequential_3/dense_9/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[ 0.19326425, -0.59375   ],
        [ 0.22846079, -0.9484353 ],
        [ 0.2872312 ,  0.0078547 ],
        [ 0.98493266,  0.81156206]], dtype=float32)>,
 <tf.Variable 'sequential_3/dense_9/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'sequential_3/dense_10/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[ 0.3122691 , -0.4607849 ,  0.9704056 ],
        [ 1.0946469 ,  0.53645396,  0.00894129]], dtype=float32)>,
 <tf.Variable 'sequential_3/dense_10/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'sequential_3/dense_11/kernel:0' shape=(3, 4) dtype=float32, numpy=
 array([[ 0.21750522,  0.13809395,  0.79373896,  0.49025977],
        [-0.8911664 ,  0.6785202 ,  0.23643327,  0.0555898 ],
        [-0.34387708, -0.7105717 ,  0.32233262,  0.8539001 ]],
       dtype=float32)>,
 <tf.Variable 'sequential_3/dense_11/bias:0

In [20]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              multiple                  10        
_________________________________________________________________
dense_10 (Dense)             multiple                  9         
_________________________________________________________________
dense_11 (Dense)             multiple                  16        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


Input object 

In [21]:
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(layers.Dense(2, activation="relu"))

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.layers

A simple alternative is to just pass an input_shape argument to your first layer:

In [23]:
model = keras.Sequential()
model.add(layers.Dense(2, activation="relu", input_shape=(4,)))

model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [24]:
print(model.weights)

[<tf.Variable 'dense_13/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.31021333, -0.08958197],
       [ 0.9117172 , -0.09146905],
       [-0.6720042 ,  0.45861864],
       [-0.2913096 , -0.57138157]], dtype=float32)>, <tf.Variable 'dense_13/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]


### Debugging workflow: add() + summary()

In [25]:
model = keras.Sequential()
model.add(keras.Input(shape=(250, 250, 3)))  # 250x250 RGB images
model.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))

model.summary()
# The answer was: (40, 40, 32), so we can keep downsampling...

model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(2))

model.summary()

# Now that we have 4x4 feature maps, time to apply global max pooling.
model.add(layers.GlobalMaxPooling2D())

# Finally, we add a classification layer.
model.add(layers.Dense(10))

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 40, 40, 32)        0         
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 121, 121, 32)      9248      
____________________________

Feature extraction with a Sequential model

In [26]:
initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

In [27]:
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers],
)

x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)

In [28]:
print(features)

[<tf.Tensor: shape=(1, 123, 123, 32), dtype=float32, numpy=
array([[[[0.        , 0.00580191, 0.31473708, ..., 0.34692615,
          0.38288027, 0.28994882],
         [0.        , 0.00580191, 0.31473708, ..., 0.34692615,
          0.38288027, 0.28994882],
         [0.        , 0.00580191, 0.31473708, ..., 0.34692615,
          0.38288027, 0.28994882],
         ...,
         [0.        , 0.00580191, 0.31473708, ..., 0.34692615,
          0.38288027, 0.28994882],
         [0.        , 0.00580191, 0.31473708, ..., 0.34692615,
          0.38288027, 0.28994882],
         [0.        , 0.00580191, 0.31473708, ..., 0.34692615,
          0.38288027, 0.28994882]],

        [[0.        , 0.00580191, 0.31473708, ..., 0.34692615,
          0.38288027, 0.28994882],
         [0.        , 0.00580191, 0.31473708, ..., 0.34692615,
          0.38288027, 0.28994882],
         [0.        , 0.00580191, 0.31473708, ..., 0.34692615,
          0.38288027, 0.28994882],
         ...,
         [0.        , 0.0058

similar method

In [29]:
initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu", name="my_intermediate_layer"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=initial_model.get_layer(name="my_intermediate_layer").output,
)
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)

In [30]:
print(features)

tf.Tensor(
[[[[0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   ...
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]]

  [[0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   ...
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]
   [0.38764647 0.261341   0.         ... 0.46727875 0.24581185
    0.2794762 ]]

  [[0.38764647 0.261341

### Transfer learning with a Sequential model

In [39]:
model = keras.Sequential([
    keras.Input(shape=(784)),
    layers.Dense(32, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(10),
])

# model.load_weights('')

In [40]:
for layer in model.layers[:-1]:
  layer.trainable = False

# model.compile(...)
# model.fit(...)

In [41]:
base_model = keras.applications.Xception(
    weights='imagenet',
    include_top=False,
    pooling='avg')

base_model.trainable = False

model = keras.Sequential([
    base_model,
    layers.Dense(1000),
])

# model.compile(...)
# model.fit(...)

83689472/83683744 [==============================] - 1s 0us/step
